### PR TITLE
Update modDesc.xml

### PR DESCRIPTION
**Pull request by Gonimy-Vetrom**

### CODE REVIEW

**Comment by Gonimy-Vetrom** [comment]
Hey. Can you do so that information about weight and units can be translated into modDesc? This is not critical, but it looks nice.
`g_currentMission:addExtraPrintText(string.format("Mass: %.1f kg", 1000*g_currentMission.player.lastFoundObjectMass))`

**Comment by loki79uk** [comment]
Hi, Yes I can add the 'Mass' text to ModDesc, I'll do it before sumbitting the update.  Is the following correct?

Mass == Массовый 
kg == кг

**Comment by Gonimy-Vetrom** [comment]
Mass == Масса
kg == кг
Thank you

**Comment by Gonimy-Vetrom** [comment]
Can I ask for one piece of advice? When there are many mods, then there are many keyboard shortcuts in the F1 menu. How can I turn them off? I've already learned them. Does this need to be changed somewhere in the script?
For example, now I use precisionFarming and this mod should report the value for manual dosage in the menu. It doesn't fit :)

**Comment by loki79uk** [comment]
So for your own mods you can either set the text visible/invisible with:
	`g_inputBinding:setActionEventTextVisibility(actionEventId, true/false)`
or you can give them higher/lower priority in the menu
	`g_inputBinding:setActionEventTextPriority(actionEventId, GS_PRIO_NORMAL)`
where:
```
GS_PRIO_VERY_HIGH = 1
GS_PRIO_HIGH = 2
GS_PRIO_NORMAL = 3
GS_PRIO_LOW = 4
GS_PRIO_VERY_LOW = 5
```
I have never tried to edit the keyboard shortcut displays for other mods if that is what you mean, but the GS_PRIO values must be stored somewhere.

edit: Or if you do not play multiplayer, then you can use these methods inside 'onRegisterActionEvents' for any mod.

**Comment by Gonimy-Vetrom** [comment]
Thank you very much!

**Review by loki79uk — APPROVED** [review]

**Pull request merged**
